Repository flucoma/learn-website, pull requests merged in 2022-03, with the labels that each got.

#234 [Content] Move sinusoidal modelling to the Sines reference
  src/routes/learn/sinusoidal-modelling.svx
  src/routes/reference/sines.svx
  static/ref/sines/dog-residual.mp3
  static/ref/sines/dog-resynth.mp3
  static/ref/sines/dog-tracks.png
  static/ref/sines/dog.mp3
  static/ref/sines/guitar-partials.svg
  static/ref/sines/synth-resynth.mp3
  static/ref/sines/synth-spectrum.png
  static/ref/sines/synth-tracks.png
  static/ref/sines/synth.mp3
Labels: content

#236 [Enhance] Waveform Views for Audio Component
  src/lib/components/Audio.svelte
Labels: enhancement

#235 [Content] OnsetSlice Reference
  package.json
  src/lib/util.js
  src/lib/widget/OnsetSlice.svelte
  src/routes/reference/onsetslice.svx
  static/audio/Tremblay-AaS-VoiceQC-B2K.mp3
  static/ref/onsetslice/delta-curve.npy
  static/ref/onsetslice/mags.npy
  static/ref/onsetslice/voice-spec.jpg
Labels: content

#240 Pitch Reference
  src/routes/reference/pitch.svx
  static/ref/pitch/220304_123101_pitch.jpg
Labels: content

#238 [Enhance] Navigation and Header Layout
  src/lib/Header.svelte
  src/lib/app.js
  src/lib/components/Crumbs.svelte
  src/lib/components/Hamburger.svelte
  src/lib/components/PopoverNav.svelte
  src/lib/components/Search.svelte
  src/lib/components/cards/Landing.svelte
  src/routes/__layout.svelte
  src/utils.css
Labels: enhancement

#253 [Enhance] Jargon/Wikilinks
  jargon.js
  package.json
  src/app.css
  src/jargon.css
  src/routes/index.svx
  svelte.config.js
  tsconfig.json
Labels: feature
